console.log("");
console.log("Diff Lib Test");
console.log("");

var file1Content;
var file2Content;

var fs = require("fs");
file1Content = fs.readFileSync("./resources/file1.txt", "utf-8");
file2Content = fs.readFileSync("./resources/file2.txt", "utf-8");

console.log("==========================================");
console.log("file1.txt");
console.log("==========================================");
console.log(file1Content);
console.log("");
console.log("==========================================");
console.log("file2.txt");
console.log("==========================================");
console.log(file2Content);
console.log("");

var file1ContentArr;
var file2ContentArr;

file1ContentArr = file1Content.split("\r\n");
file2ContentArr = file2Content.split("\r\n");

var difflib = require("difflib");

var diff = difflib.unifiedDiff(file1ContentArr, file2ContentArr, 
{ fromfile: 'Original',
tofile: 'Current',
lineterm: ''
});
 
console.log("==========================================");
console.log("Diff Unified Format generated by Diff Lib");
console.log("==========================================");
console.log(diff);
 
 fs.writeFile("output/diff.json", JSON.stringify(diff), function(err){
   if (err) {
       return console.error(err);
   }
 });
 
 
 